const {
  REACT_APP_ADDRESS,
  REACT_APP_PRIVATE_KEY,
  REACT_APP_RPC_URL,
  REACT_APP_ACCESS_KEY,
  REACT_APP_SECRET_ACCESS_KEY,
} = process.env;

export {
  REACT_APP_ADDRESS,
  REACT_APP_PRIVATE_KEY,
  REACT_APP_RPC_URL,
  REACT_APP_ACCESS_KEY,
  REACT_APP_SECRET_ACCESS_KEY,
};
